version: '3.1'
services:
  xss:
    build: .
    ports:
      - "80"
    links:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hunter123
      - DB_HOST=mysql
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=hunter123
      - MYSQL_DATABASE=db
